[2019-05-09 10:54:01] local.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Uncaught TypeError: Argument 1 passed to App\Exceptions\Handler::report() must be an instance of Exception, instance of ParseError given, called in C:\wamp64\www\memory\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php on line 73 and defined in C:\wamp64\www\memory\app\Exceptions\Handler.php:49
Stack trace:
#0 C:\wamp64\www\memory\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(73): App\Exceptions\Handler->report(Object(ParseError))
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(ParseError))
#2 {main}
  thrown in C:\wamp64\www\memory\app\Exceptions\Handler.php:49
Stack trace:
#0 C:\wamp64\www\memory\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(130): Symfony\Component\Debug\Exception\FatalErrorException->__construct()
#1 C:\wamp64\www\memory\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(116): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError()
#2 C:\wamp64\www\memory\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(0): Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#3 {main}  
[2019-05-09 10:56:55] local.ERROR: InvalidArgumentException: Command "cache:clean" is not defined.

Did you mean one of these?
    cache:clear
    config:clear
    route:clear
    cache:table in C:\wamp64\www\memory\vendor\symfony\console\Symfony\Component\Console\Application.php:549
Stack trace:
#0 C:\wamp64\www\memory\vendor\symfony\console\Symfony\Component\Console\Application.php(192): Symfony\Component\Console\Application->find('cache:clean')
#1 C:\wamp64\www\memory\vendor\symfony\console\Symfony\Component\Console\Application.php(126): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 C:\wamp64\www\memory\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(94): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 C:\wamp64\www\memory\artisan(69): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 {main}  
[2019-05-09 10:57:44] local.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Uncaught TypeError: Argument 1 passed to App\Exceptions\Handler::report() must be an instance of Exception, instance of ParseError given, called in C:\wamp64\www\memory\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php on line 73 and defined in C:\wamp64\www\memory\app\Exceptions\Handler.php:49
Stack trace:
#0 C:\wamp64\www\memory\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(73): App\Exceptions\Handler->report(Object(ParseError))
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(ParseError))
#2 {main}
  thrown in C:\wamp64\www\memory\app\Exceptions\Handler.php:49
Stack trace:
#0 C:\wamp64\www\memory\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(130): Symfony\Component\Debug\Exception\FatalErrorException->__construct()
#1 C:\wamp64\www\memory\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(116): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError()
#2 C:\wamp64\www\memory\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(0): Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#3 {main}  
[2019-05-09 10:58:06] local.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Uncaught TypeError: Argument 1 passed to App\Exceptions\Handler::report() must be an instance of Exception, instance of ParseError given, called in C:\wamp64\www\memory\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php on line 73 and defined in C:\wamp64\www\memory\app\Exceptions\Handler.php:49
Stack trace:
#0 C:\wamp64\www\memory\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(73): App\Exceptions\Handler->report(Object(ParseError))
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(ParseError))
#2 {main}
  thrown in C:\wamp64\www\memory\app\Exceptions\Handler.php:49
Stack trace:
#0 C:\wamp64\www\memory\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(130): Symfony\Component\Debug\Exception\FatalErrorException->__construct()
#1 C:\wamp64\www\memory\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(116): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError()
#2 C:\wamp64\www\memory\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(0): Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#3 {main}  
[2019-05-09 10:58:35] local.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Uncaught TypeError: Argument 1 passed to App\Exceptions\Handler::report() must be an instance of Exception, instance of ParseError given, called in C:\wamp64\www\memory\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php on line 73 and defined in C:\wamp64\www\memory\app\Exceptions\Handler.php:49
Stack trace:
#0 C:\wamp64\www\memory\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(73): App\Exceptions\Handler->report(Object(ParseError))
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(ParseError))
#2 {main}
  thrown in C:\wamp64\www\memory\app\Exceptions\Handler.php:49
Stack trace:
#0 C:\wamp64\www\memory\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(130): Symfony\Component\Debug\Exception\FatalErrorException->__construct()
#1 C:\wamp64\www\memory\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(116): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError()
#2 C:\wamp64\www\memory\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(0): Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#3 {main}  
